apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkc-1
  namespace: hakan
spec:
  distribution:
    version: v1.18
  topology:
    controlPlane:
      class: guaranteed-small
      count: 1
      storageClass: k8s-policy
    workers:
      class: guaranteed-small
      count: 3
      storageClass: k8s-policy
